### ISSUE TITLE
Support js file extension

### ISSUE THREAD

**Issue by iamyuu** [alloc/vite-react-jsx#13]
<img width="331" alt="Screen Shot 2021-08-30 at 09 58 36" src="https://user-images.githubusercontent.com/45778229/131278895-9cbd254a-acd9-492c-b2ed-9c40e556e828.png">

I'm using an admin template that uses js file extension and not imported React on each file, I already config Vite to also transform jsx inside js file, but it really pains if I need to import React on each file, so I think be better to also support js extension

**Comment by aleclarson** [comment]
See #2
