### ISSUE TITLE
Possible to use js instead of jsx?

### ISSUE THREAD

**Issue by myckhel** [alloc/vite-react-jsx#2]
Is it possible to use js extension  instead of jsx extension using this library?

**Comment by aleclarson** [comment]
Nope, and not planning on it. The `@vitejs/react-refresh` plugin doesn't allow it either ([see here](https://github.com/vitejs/vite/blob/8b4075d6fe1628ec2a91b16ba51bdfd441dfc328/packages/plugin-react-refresh/index.js#L72-L74)). Also, running the Babel transform on every single JS module probably slows down builds quite a bit (though I haven't tested).

**Comment by myckhel** [comment]
Alright!
