### ISSUE TITLE
Unable to get this working with optimizeDeps and custom alias paths

### ISSUE THREAD

**Issue by eddeee888** [alloc/vite-react-jsx#9]
Hello! Thanks for making this package! It's helping me with my setup quite a bit.

I have a question about this package when used with `tsconfig.json`'s alias path and Vite's `optimizeDeps`. 

Here's my setup:

- This package is used as a plugin to help JSX transform.
- `tsconfig.json`'s alias path is used to point to a local package. In the code it's `@/shared/ui`
- A plugin called [vite-tsconfig-paths](https://github.com/aleclarson/vite-tsconfig-paths) is used to resolve the path.

Now this setup is working but it's loading all my files in `@/shared/ui` individually so I'd like to pre-bundle `@/shared/ui` using `optimizeDeps`

However, this problem happens at runtime: when `optimizeDeps` is used, I need to put in `import React` line in all files exported by `@/shared/ui`

Am I using this plugin wrong ? Do you have suggestions/workaround?

My setup can be seen here: https://github.com/eddeee888/vite-react-jsx/tree/optimize-deps-usage

**Comment by aleclarson** [comment]
Hey, I don't know when I'll get to this. Hopefully someone else can investigate and report back here.

**Comment by aleclarson** [comment]
Now that `@vitejs/plugin-react` is released, could you please report this issue on the official Vite repo?

**Comment by eddeee888** [comment]
Cheers! Will do!
